version: '3'

services:
  ezze_nps-front:
    image: nps-front
    build:
      context: .
    ports:
      - "5173:5173"  
    environment:
      VITE_API_URL: "http://api.example.com"
    networks:
      - ezze-network

networks:
  ezze-network:
    driver: bridge
